[[redirects]]
  from   = "/webhook"
  to     = "https://ts21.cloud1c.pro/gourme_container/hs/ContainerKK"
  status = 200          # proxy
  force  = true

  [redirects.headers]
    Access-Control-Allow-Origin = "https://qrcoderkenkost.netlify.app/"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
