<<<<<<< HEAD
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[redirects]]
  from   = "/api/container"
  to     = "https://ts21.cloud1c.pro/gourme_container/hs/GourmetContainer"
  status = 200
  force  = true
  [redirects.headers]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "POST"
    Access-Control-Allow-Headers = "Content-Type, Authoriztion"
=======
[[redirects]]
  from   = "/webhook"
  to     = "https://ts21.cloud1c.pro/gourme_container/hs/ContainerKK"
  status = 200          # proxy
  force  = true

  [redirects.headers]
    Access-Control-Allow-Origin = "https://qrcoderkenkost.netlify.app/"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
>>>>>>> ccb78b292debe38689c373fcf0ff29cc43c2bbe0
